CREATE DATABASE MU_CENTRALIZED_SCHEDULING;
 
USE MU_CENTRALIZED_SCHEDULING;

CREATE TABLE USERS (
    user_id CHAR(6) NOT NULL,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(100) NOT NULL,
    first_name VARCHAR(50) NOT NULL,
    middle_name VARCHAR(50),
    last_name VARCHAR(50) NOT NULL,
    CONSTRAINT PK_USERS_USER_ID PRIMARY KEY (user_id)
);

CREATE TABLE ROLES (
    role_id CHAR(2) NOT NULL,
    role_name VARCHAR(50) NOT NULL,
    role_description VARCHAR(100),
    CONSTRAINT PK_ROLES_ROLE_ID PRIMARY KEY (role_id)
);

CREATE TABLE USER_ROLES (
	user_id CHAR(6) NOT NULL,
    role_id CHAR(2) NOT NULL,
    CONSTRAINT FK_USER_ROLES_USER_ID FOREIGN KEY (user_id)
    REFERENCES USERS(user_id),
    CONSTRAINT FK_USER_ROLES_ROLE_ID FOREIGN KEY (role_id)
    REFERENCES ROLES(role_id),
	CONSTRAINT PK_USER_ROLES_IDS PRIMARY KEY (user_id, role_id)
);

CREATE TABLE ROOMS (
    room_id CHAR(4) NOT NULL,
    room_name VARCHAR(50) NOT NULL,
    capacity INT NOT NULL,
    CONSTRAINT PK_ROOMS_ROOM_ID PRIMARY KEY (room_id)
);


CREATE TABLE ROOM_BOOKINGS (
	booking_id CHAR(6) NOT NULL,
	user_id CHAR(6) NOT NULL,
    room_id CHAR(4) NOT NULL,
    approved_ind CHAR(1) NOT NULL,
    booking_reason VARCHAR(200) NOT NULL,
    date_booked DATETIME NOT NULL,
    from_booking DATETIME NOT NULL,
    to_booking DATETIME NOT NULL,
    remarks VARCHAR(200) NOT NULL,
	CONSTRAINT FK_ROOM_BOOKINGS_USER_ID FOREIGN KEY (user_id)
    REFERENCES USERS(user_id),
    CONSTRAINT FK_ROOM_BOOKINGS_ROOM_ID FOREIGN KEY (room_id)
    REFERENCES ROOMS(room_id)
);

-- drop table room_bookings
-- DROP TABLE USERS, ROLES, USER_ROLES, ROOMS, ROOM_BOOKINGS